/// <reference types="leaflet" />
import { EventEmitter, OnDestroy } from '@angular/core';
import { ImageOverlay, LatLngBoundsExpression, Event, PopupEvent, TooltipEvent, LatLngBounds } from 'leaflet';
import { MapComponent } from './map.component';
export declare class ImageOverlayDirective extends ImageOverlay implements OnDestroy {
    urlChange: EventEmitter<string>;
    displayChange: EventEmitter<boolean>;
    opacityChange: EventEmitter<number>;
    boundsChange: EventEmitter<LatLngBounds>;
    northChange: EventEmitter<number>;
    eastChange: EventEmitter<number>;
    southChange: EventEmitter<number>;
    westChange: EventEmitter<number>;
    addEvent: EventEmitter<Event>;
    removeEvent: EventEmitter<Event>;
    popupopenEvent: EventEmitter<PopupEvent>;
    popupcloseEvent: EventEmitter<PopupEvent>;
    tooltipopenEvent: EventEmitter<TooltipEvent>;
    tooltipcloseEvent: EventEmitter<TooltipEvent>;
    clickEvent: EventEmitter<MouseEvent>;
    dbclickEvent: EventEmitter<MouseEvent>;
    mousedownEvent: EventEmitter<MouseEvent>;
    mouseoverEvent: EventEmitter<MouseEvent>;
    mouseoutEvent: EventEmitter<MouseEvent>;
    contextmenuEvent: EventEmitter<MouseEvent>;
    constructor(mapComponent: MapComponent);
    ngOnDestroy(): void;
    setUrl(url: string): this;
    url: string;
    setOpacity(val: number): this;
    opacity: number;
    display: boolean;
    setBounds(val: LatLngBoundsExpression): this;
    bounds: LatLngBounds;
    north: number;
    east: number;
    south: number;
    west: number;
    crossOrigin: boolean;
    alt: string;
    interactive: boolean;
    attribution: string;
}
